fix: Add config entry for slideshow
pop-os/cosmic-settings pull request #236
Opened 2024-04-11 02:46 UTC by joshuamegnauth54

Closes: #169

2024-04-11 09:14 UTC, mmstick requested changes
This would be out of sync with cosmic-bg. It already gets slideshow state from cosmic-bg's config. The slideshow feature is enabled when the background is a path.

2024-04-12 04:17 UTC, joshuamegnauth54 commented
Good point. I updated the code to get the slideshow status from cosmic-bg.

The final code is much simpler than my first attempt.

2024-04-12 10:15 UTC, mmstick approved these changes

2024-04-12 10:15 UTC, merged

2024-04-12 10:15 UTC, mmstick commented
Thanks!