Update cosmic_settings.ftl for 'es-419' to align with 'en' file
pop-os/cosmic-settings pull request #687
Opened 2024-10-10 07:01 UTC by SotoAugusto

I had to move some lines around to be 1:1 with the 'en' file.

2024-10-22 15:40 UTC, mmstick requested changes
Text for font configuration changed

2024-10-22 15:40 UTC, mmstick commented on i18n/es-419/cosmic-settings.ftl
> +font-weight = Grosor
Not used anymore

2024-10-22 15:40 UTC, mmstick commented on i18n/es-419/cosmic-settings.ftl
> +    .oblique = Oblicua
Same

2024-10-22 15:40 UTC, mmstick commented on i18n/es-419/cosmic-settings.ftl
> +    .expanded = Expandido
Same

2024-10-24 04:40 UTC, SotoAugusto commented
> Text for font configuration changed

Done requested changes

2024-10-24 15:23 UTC, mmstick approved these changes

2024-10-24 15:24 UTC, merged