Update cosmic_settings.ftl
pop-os/cosmic-settings pull request #715
Opened 2024-10-22 15:49 UTC by bittin

Solve Merge conflict with the Swedish translation

2024-10-22 15:54 UTC, mmstick requested changes

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +    .extra-bold = Extra fet
These do not exist anymore

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +    .oblique = Sned
These do not exist anymore

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +    .expanded = Expanderad
These do not exist anymore

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +>>>>>>> master
Merge conflict syntax left over

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +font-family = Teckensnittsfamilj
Not used

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +monospace-font = Monospace teckensnitt
Duplicate variable

2024-10-22 15:54 UTC, mmstick commented on i18n/sv/cosmic_settings.ftl
> +interface-font = System teckensnitt
Duplicate variable

2024-10-22 16:01 UTC, bittin commented
Sorry, should look at this properly when i have more time, would be good with https://weblate.org/en-gb/ 
https://hosted.weblate.org/ or a translation system instead of doing everything manually tbh

2024-10-27 05:40 UTC, closed without merging

2024-10-27 05:42 UTC, bittin commented
to much mess see #725 instead for now